# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

def networkAndRxPods
  pod 'RxAlamofire', '~> 5'
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
end

def firebasePods
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Crashlytics'
end

def utilityPods
  pod 'RealmSwift', '~>10'
  pod 'SwiftyStarRatingView', '~> 1.0'
  pod 'lottie-ios', '3.1.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'R.swift'
  pod 'BottomPopup'
  #Rx Datasources for TableViews and UICollectionViews
  pod 'RxDataSources', '~> 4.0'
  pod 'RangeSeekSlider'
  pod 'SVPinView', '~> 1.0'
  pod "AttributedStringBuilder"
  pod 'PopupDialog'
  pod 'MarqueeLabel'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDWebImageSVGKitPlugin'
  pod "WARangeSlider"
  pod 'IQKeyboardManagerSwift'
  #pod 'FittedSheets'
  pod 'Cosmos', '~> 21.0'
  pod 'DropDown'
  pod 'HorizontalProgressBar'
  pod 'DeviceKit', '~> 4.0'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Swinject'
  pod 'DatePickerDialog'
  pod 'DZNEmptyDataSet'
end


target 'TutorBuddy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TutorBuddy
  networkAndRxPods
  firebasePods
  utilityPods

  target 'TutorBuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TutorBuddyUITests' do
    # Pods for testing
  end

end
